### ISSUE TITLE
java.lang.IllegalStateException: Cause already initialized , cause crash!

### ISSUE THREAD

**Issue by microstudent** [T-Spoon/Traceur#6]
Hi, I am trying to use Traceur in my project, it work fine until it cause an crash. It crash on Subscriber.onError(), so Rxjava cannot handle it anymore.
After disabling Traceur, it just logout the error and doesn't crash.

It happened when I used Charles to capture some https request without import certificate.
there is the crash log:
***
`
08-23 14:59:31.629 W/System.err(18773):   ComposedException 1 :
08-23 14:59:31.629 W/System.err(18773):         javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
08-23 14:59:31.629 W/System.err(18773):                 at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:333)
08-23 14:59:31.629 W/System.err(18773):                 at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:281)
08-23 14:59:31.629 W/System.err(18773):                 at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:251)
08-23 14:59:31.629 W/System.err(18773):                 at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:151)
08-23 14:59:31.629 W/System.err(18773):                 at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:195)
08-23 14:59:31.629 W/System.err(18773):                 at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:121)
08-23 14:59:31.629 W/System.err(18773):                 at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:100)
08-23 14:59:31.629 W/System.err(18773):                 at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
08-23 14:59:31.629 W/System.err(18773):                 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
08-23 14:59:31.629 W/System.err(18773):                 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
08-23 14:59:31.629 W/System.err(18773):                 at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
08-23 14:59:31.629 W/System.err(18773):                 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
08-23 14:59:31.630 W/System.err(18773):                 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
08-23 14:59:31.630 W/System.err(18773):                 at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
08-23 14:59:31.630 W/System.err(18773):                 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
08-23 14:59:31.630 W/System.err(18773):                 at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
08-23 14:59:31.630 W/System.err(18773):                 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
08-23 14:59:31.630 W/System.err(18773):                 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
08-23 14:59:31.630 D/libc-netbsd(18773): [getaddrinfo]: mtk hostname=abc.xxx.com; servname=(null); netid=0; mark=0
08-23 14:59:31.630 W/System.err(18773):                 at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:211)
08-23 14:59:31.630 W/System.err(18773):                 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
08-23 14:59:31.630 D/libc-netbsd(18773): getaddrinfo( app_uid:10117
08-23 14:59:31.630 W/System.err(18773):                 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
08-23 14:59:31.630 W/System.err(18773):                 at com.xxxx.data.net.intercept.CacheInterceptor.intercept(CacheInterceptor.java:27)
08-23 14:59:31.630 D/libc-netbsd(18773): getaddrinfo() uid prop:
08-23 14:59:31.630 W/System.err(18773):                 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
08-23 14:59:31.630 W/System.err(18773):                 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
08-23 14:59:31.630 D/libc-netbsd(18773): getaddrinfo() getuid():10117
08-23 14:59:31.630 W/System.err(18773):                 at com.xxx.okhttp.GslbHttpClient.performRequest(GslbHttpClient.java:34)
08-23 14:59:31.630 D/libc-netbsd(18773): [getaddrinfo]: mtk ai_addrlen=0; ai_canonname=(null); ai_flags=4; ai_family=0
08-23 14:59:31.630 W/System.err(18773):                 at com.xxx.HttpClientProxy.performRequest(HttpClientProxy.java:86)
08-23 14:59:31.630 W/System.err(18773):                 at com.xxx.okhttp.GslbInterceptor.intercept(GslbInterceptor.java:36)
08-23 14:59:31.630 W/System.err(18773):                 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
08-23 14:59:31.630 W/System.err(18773):                 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
08-23 14:59:31.630 W/System.err(18773):                 at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
08-23 14:59:31.630 W/System.err(18773):                 at okhttp3.RealCall.execute(RealCall.java:69)
08-23 14:59:31.630 W/System.err(18773):                 at retrofit2.OkHttpCall.execute(OkHttpCall.java:180)
08-23 14:59:31.630 W/System.err(18773):                 at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:41)
08-23 14:59:31.630 W/System.err(18773):                 at io.reactivex.Observable.subscribe(Observable.java:10901)
08-23 14:59:31.630 D/NativeCrypto(18773): ssl=0xd90e9800 NativeCrypto_SSL_do_handshake fd=0xdb08efc0 shc=0xdb08efc4 timeout_millis=30000 client_mode=1 npn=0x0
08-23 14:59:31.630 W/System.err(18773):                 at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
08-23 14:59:31.630 W/System.err(18773):                 at io.reactivex.Observable.subscribe(Observable.java:10901)
08-23 14:59:31.630 D/NativeCrypto(18773): doing handshake ++
08-23 14:59:31.630 W/System.err(18773):                 at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
08-23 14:59:31.630 W/System.err(18773):                 at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:452)
08-23 14:59:31.630 D/NativeCrypto(18773): ssl=0xd90e9800 info_callback where=0x10 ret=1
08-23 14:59:31.630 W/System.err(18773):                 at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
08-23 14:59:31.630 D/NativeCrypto(18773): ssl=0xd90e9800 handshake start in CINIT  before connect initialization
08-23 14:59:31.630 W/System.err(18773):                 at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
08-23 14:59:31.630 W/System.err(18773):                 at java.util.concurrent.FutureTask.run(FutureTask.java:237)
08-23 14:59:31.630 W/System.err(18773):                 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
08-23 14:59:31.630 D/NativeCrypto(18773): ssl=0xd90e9800 info_callback calling handshakeCompleted
08-23 14:59:31.630 W/System.err(18773):                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
08-23 14:59:31.630 W/System.err(18773):                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
08-23 14:59:31.630 D/NativeCrypto(18773): ssl=0xd90e9800 info_callback completed
08-23 14:59:31.630 W/System.err(18773):                 at java.lang.Thread.run(Thread.java:818)
08-23 14:59:31.630 W/System.err(18773):         Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
08-23 14:59:31.630 D/NativeCrypto(18773): ssl=0xd90e9800 info_callback where=0x1001 ret=1
08-23 14:59:31.630 W/System.err(18773):                 at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:324)
08-23 14:59:31.630 D/NativeCrypto(18773): ssl=0xd90e9800 SSL_connect:CINIT  before connect initialization
08-23 14:59:31.630 W/System.err(18773):                 at com.android.org.conscrypt.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java:225)
08-23 14:59:31.631 W/System.err(18773):                 at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:115)
08-23 14:59:31.631 D/NativeCrypto(18773): ssl=0xd90e9800 info_callback ignored
08-23 14:59:31.631 W/System.err(18773):                 at com.android.org.conscrypt.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:571)
08-23 14:59:31.631 W/System.err(18773):                 at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
08-23 14:59:31.631 W/System.err(18773):                 at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:329)
08-23 14:59:31.631 W/System.err(18773):                 at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:281)
08-23 14:59:31.631 W/System.err(18773):                 at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:251)
08-23 14:59:31.631 W/System.err(18773):                 at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:151)
08-23 14:59:31.631 W/System.err(18773):                 at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:195)
08-23 14:59:31.631 W/System.err(18773):                 at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:121)
08-23 14:59:31.631 W/System.err(18773):                 at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:100)
08-23 14:59:31.631 W/System.err(18773):                 at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
08-23 14:59:31.631 W/System.err(18773):                 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
08-23 14:59:31.631 D/NativeCrypto(18773): ssl=0xd90e9800 info_callback where=0x1001 ret=1
08-23 14:59:31.631 W/System.err(18773):                 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
08-23 14:59:31.631 W/System.err(18773):                 at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
08-23 14:59:31.631 D/NativeCrypto(18773): ssl=0xd90e9800 SSL_connect:3WCH_A SSLv3 write client hello A
08-23 14:59:31.631 W/System.err(18773):                 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
08-23 14:59:31.631 D/NativeCrypto(18773): ssl=0xd90e9800 info_callback ignored
08-23 14:59:31.631 W/System.err(18773):                 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
08-23 14:59:31.631 W/System.err(18773):                 at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
08-23 14:59:31.631 W/System.err(18773):                 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
08-23 14:59:31.631 D/NativeCrypto(18773): ssl=0xd90e9800 info_callback where=0x1002 ret=-1
08-23 14:59:31.631 W/System.err(18773):                 at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
08-23 14:59:31.631 D/NativeCrypto(18773): ssl=0xd90e9800 SSL_connect:error exit in 3RSH_A SSLv3 read server hello A
08-23 14:59:31.631 W/System.err(18773):                 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
08-23 14:59:31.631 D/NativeCrypto(18773): ssl=0xd90e9800 info_callback ignored
08-23 14:59:31.631 W/System.err(18773):                 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
08-23 14:59:31.631 W/System.err(18773):                 at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:211)
08-23 14:59:31.631 D/NativeCrypto(18773): doing handshake -- ret=-1
08-23 14:59:31.631 W/System.err(18773):                 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
08-23 14:59:31.631 W/System.err(18773):                 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
08-23 14:59:31.631 W/System.err(18773):                 at com.xxxx.data.net.intercept.CacheInterceptor.intercept(CacheInterceptor.java:27)
08-23 14:59:31.631 D/NativeCrypto(18773): ssl=0xd90e9800 NativeCrypto_SSL_do_handshake ret=-1 errno=11 sslError=2 timeout_millis=30000
08-23 14:59:31.631 W/System.err(18773):                 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
08-23 14:59:31.631 W/System.err(18773):                 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
08-23 14:59:31.631 W/System.err(18773):                 at com.xxx.okhttp.GslbHttpClient.performRequest(GslbHttpClient.java:34)
08-23 14:59:31.631 W/System.err(18773):                 at com.xxx.HttpClientProxy.performRequest(HttpClientProxy.java:86)
08-23 14:59:31.631 W/System.err(18773):                 at com.xxx.okhttp.GslbInterceptor.intercept(GslbInterceptor.java:36)
08-23 14:59:31.631 W/System.err(18773):                 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
08-23 14:59:31.631 W/System.err(18773):                 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
08-23 14:59:31.631 W/System.err(18773):                 at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
08-23 14:59:31.631 W/System.err(18773):                 at okhttp3.RealCall.execute(RealCall.java:69)
08-23 14:59:31.631 W/System.err(18773):                 at retrofit2.OkHttpCall.execute(OkHttpCall.java:180)
08-23 14:59:31.631 W/System.err(18773):                 at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:41)
08-23 14:59:31.631 W/System.err(18773):                 at io.reactivex.Observable.subscribe(Observable.java:10901)
08-23 14:59:31.631 W/System.err(18773):                 at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
08-23 14:59:31.632 W/System.err(18773):                 at io.reactivex.Observable.subscribe(Observable.java:10901)
08-23 14:59:31.632 W/System.err(18773):                 at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
08-23 14:59:31.632 W/System.err(18773):                 at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:452)
08-23 14:59:31.632 W/System.err(18773):                 at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
08-23 14:59:31.632 W/System.err(18773):                 at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
08-23 14:59:31.632 W/System.err(18773):                 at java.util.concurrent.FutureTask.run(FutureTask.java:237)
08-23 14:59:31.632 W/System.err(18773):                 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
08-23 14:59:31.632 W/System.err(18773):                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
08-23 14:59:31.632 W/System.err(18773):                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
08-23 14:59:31.632 W/System.err(18773):                 at java.lang.Thread.run(Thread.java:818)
08-23 14:59:31.632 W/System.err(18773):         Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
08-23 14:59:31.632 W/System.err(18773):                 at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:324)
08-23 14:59:31.632 W/System.err(18773):                 at com.android.org.conscrypt.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java:225)
08-23 14:59:31.632 W/System.err(18773):                 at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:115)
08-23 14:59:31.632 W/System.err(18773):                 at com.android.org.conscrypt.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:571)
08-23 14:59:31.632 W/System.err(18773):                 at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
08-23 14:59:31.632 W/System.err(18773):                 at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:329)
08-23 14:59:31.632 W/System.err(18773):                 at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:281)
08-23 14:59:31.632 W/System.err(18773):                 at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:251)
08-23 14:59:31.632 W/System.err(18773):                 at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:151)
08-23 14:59:31.632 D/ConnectivityService( 1155): getActiveNetworkInfo networkInfo = [type: WIFI[], state: CONNECTED/CONNECTED, reason: (unspecified), extra: "xx-xxx-2.4G", roaming: false, failover: false, isAvailable: true]
08-23 14:59:31.632 W/System.err(18773):                 at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:195)
08-23 14:59:31.632 W/System.err(18773):                 at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:121)
08-23 14:59:31.632 W/System.err(18773):                 at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:100)
08-23 14:59:31.632 W/System.err(18773):                 at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
08-23 14:59:31.632 W/System.err(18773):                 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
08-23 14:59:31.632 W/System.err(18773):                 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
08-23 14:59:31.632 W/System.err(18773):                 at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
08-23 14:59:31.632 W/System.err(18773):                 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
08-23 14:59:31.632 W/System.err(18773):                 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
08-23 14:59:31.632 W/System.err(18773):                 at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
08-23 14:59:31.632 W/System.err(18773):                 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
08-23 14:59:31.632 W/System.err(18773):                 at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
08-23 14:59:31.632 W/System.err(18773):                 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
08-23 14:59:31.632 W/System.err(18773):                 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
08-23 14:59:31.632 W/System.err(18773):                 at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:211)
08-23 14:59:31.632 W/System.err(18773):                 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
08-23 14:59:31.633 W/System.err(18773):                 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
08-23 14:59:31.633 W/System.err(18773):                 at com.xxxx.data.net.intercept.CacheInterceptor.intercept(CacheInterceptor.java:27)
08-23 14:59:31.633 W/System.err(18773):                 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
08-23 14:59:31.633 W/System.err(18773):                 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
08-23 14:59:31.633 W/System.err(18773):                 at com.xxx.okhttp.GslbHttpClient.performRequest(GslbHttpClient.java:34)
08-23 14:59:31.633 W/System.err(18773):                 at com.xxx.HttpClientProxy.performRequest(HttpClientProxy.java:86)
08-23 14:59:31.633 W/System.err(18773):                 at com.xxx.okhttp.GslbInterceptor.intercept(GslbInterceptor.java:36)
08-23 14:59:31.633 W/System.err(18773):                 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
08-23 14:59:31.633 W/System.err(18773):                 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
08-23 14:59:31.633 W/System.err(18773):                 at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
08-23 14:59:31.633 W/System.err(18773):                 at okhttp3.RealCall.execute(RealCall.java:69)
08-23 14:59:31.633 W/System.err(18773):                 at retrofit2.OkHttpCall.execute(OkHttpCall.java:180)
08-23 14:59:31.633 W/System.err(18773):                 at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:41)
08-23 14:59:31.633 W/System.err(18773):                 at io.reactivex.Observable.subscribe(Observable.java:10901)
08-23 14:59:31.633 W/System.err(18773):                 at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
08-23 14:59:31.633 W/System.err(18773):                 at io.reactivex.Observable.subscribe(Observable.java:10901)
08-23 14:59:31.633 W/System.err(18773):                 at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
08-23 14:59:31.633 W/System.err(18773):                 at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:452)
08-23 14:59:31.633 W/System.err(18773):                 at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
08-23 14:59:31.633 W/System.err(18773):                 at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
08-23 14:59:31.633 W/System.err(18773):                 at java.util.concurrent.FutureTask.run(FutureTask.java:237)
08-23 14:59:31.633 W/System.err(18773):                 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
08-23 14:59:31.633 W/System.err(18773):                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
08-23 14:59:31.633 W/System.err(18773):                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
08-23 14:59:31.633 W/System.err(18773):                 at java.lang.Thread.run(Thread.java:818)
08-23 14:59:31.633 W/System.err(18773):   ComposedException 2 :
08-23 14:59:31.633 W/System.err(18773):         java.lang.IllegalStateException: Cause already initialized
08-23 14:59:31.633 W/System.err(18773):                 at com.tspoon.traceur.ObservableOnAssembly$OnAssemblyObserver.onError(ObservableOnAssembly.java:62)
08-23 14:59:31.633 W/System.err(18773):                 at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeOnObserver.onError(ObservableSubscribeOn.java:63)
08-23 14:59:31.633 W/System.err(18773):                 at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onError(BodyObservable.java:72)
08-23 14:59:31.633 W/System.err(18773):                 at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:55)
08-23 14:59:31.633 W/System.err(18773):                 at io.reactivex.Observable.subscribe(Observable.java:10901)
08-23 14:59:31.633 W/System.err(18773):                 at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
08-23 14:59:31.633 W/System.err(18773):                 at io.reactivex.Observable.subscribe(Observable.java:10901)
08-23 14:59:31.633 W/System.err(18773):                 at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
08-23 14:59:31.634 W/System.err(18773):                 at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:452)
08-23 14:59:31.634 W/System.err(18773):                 at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
08-23 14:59:31.634 W/System.err(18773):                 at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
08-23 14:59:31.634 W/System.err(18773):                 at java.util.concurrent.FutureTask.run(FutureTask.java:237)
08-23 14:59:31.634 W/System.err(18773):                 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
08-23 14:59:31.634 W/System.err(18773):                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
08-23 14:59:31.634 W/System.err(18773):                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
08-23 14:59:31.634 W/System.err(18773):                 at java.lang.Thread.run(Thread.java:818)
`

**Comment by nicai1900** [comment]
@microstudent 

Did you fix it?
